### PR TITLE
Add 10 bit support for first pass

### PR DESCRIPTION
**Pull request by galenlynch**
Allow high bit-depth inputs to save to 10 bits

Needs to be tested

### CODE REVIEW

**Comment by galenlynch** [comment]
I have tested on my end but it wasn't clear to me if things are working as expected with bonsai and higher bit depths. @bruno-f-cruz if you can get bonsai to work (when you're back?) can you test this?

Either way, I think this is a good online encoder for 10+ bit depths, and seems to work on my end. I will double check with gray pixels.

**Comment by bruno-f-cruz** [comment]
> I have tested on my end but it wasn't clear to me if things are working as expected with bonsai and higher bit depths. @bruno-f-cruz if you can get bonsai to work (when you're back?) can you test this?
> 
> Either way, I think this is a good online encoder for 10+ bit depths, and seems to work on my end. I will double check with gray pixels.

Ye to summarize, Bonsai/Spinnaker can do 16bit with the following caveats:

The spinnaker SDK version we are using doesn't seem to provide a 10p->Mono16 conversion, so you need to set the camera pixel_format to Mono16;
I couldn't find a raw opencv codec (right now we are using DIB) that handles mono16. In the future, we may just want to save the video to a flat binary file, but i am not sure if ffmpeg supports streaming from binary files?
The operator and video benchmarks are ready to run this string as a test, all people need to do is copy paste it. I will run a quick tests on my end and send you the videos later. Thanks!

**Comment by galenlynch** [comment]
Log from Bruno's test acquisition with Mono16 pixel format:
```
ffmpeg version 7.0-full_build-[www.gyan.dev](https://www.gyan.dev/) Copyright (c) 2000-2024 the FFmpeg developers
  built with gcc 13.2.0 (Rev5, Built by MSYS2 project)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-w32threads --disable-autodetect --enable-fontconfig --enable-iconv --enable-gnutls --enable-libxml2 --enable-gmp --enable-bzlib --enable-lzma --enable-libsnappy --enable-zlib --enable-librist --enable-libsrt --enable-libssh --enable-libzmq --enable-avisynth --enable-libbluray --enable-libcaca --enable-sdl2 --enable-libaribb24 --enable-libaribcaption --enable-libdav1d --enable-libdavs2 --enable-libuavs3d --enable-libxevd --enable-libzvbi --enable-librav1e --enable-libsvtav1 --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxavs2 --enable-libxeve --enable-libxvid --enable-libaom --enable-libjxl --enable-libopenjpeg --enable-libvpx --enable-mediafoundation --enable-libass --enable-frei0r --enable-libfreetype --enable-libfribidi --enable-libharfbuzz --enable-liblensfun --enable-libvidstab --enable-libvmaf --enable-libzimg --enable-amf --enable-cuda-llvm --enable-cuvid --enable-dxva2 --enable-d3d11va --enable-d3d12va --enable-ffnvcodec --enable-libvpl --enable-nvdec --enable-nvenc --enable-vaapi --enable-libshaderc --enable-vulkan --enable-libplacebo --enable-opencl --enable-libcdio --enable-libgme --enable-libmodplug --enable-libopenmpt --enable-libopencore-amrwb --enable-libmp3lame --enable-libshine --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libcodec2 --enable-libilbc --enable-libgsm --enable-libopencore-amrnb --enable-libopus --enable-libspeex --enable-libvorbis --enable-ladspa --enable-libbs2b --enable-libflite --enable-libmysofa --enable-librubberband --enable-libsoxr --enable-chromaprint
 
libavutil      59.  8.100 / 59.  8.100
libavcodec     61.  3.100 / 61.  3.100
libavformat    61.  1.100 / 61.  1.100
libavdevice    61.  1.100 / 61.  1.100
libavfilter    10.  1.100 / 10.  1.100
libswscale      8.  1.100 /  8.  1.100
libswresample   5.  1.100 /  5.  1.100
libpostproc    58.  1.100 / 58.  1.100
 
Input #0, rawvideo, from '\\\\.\\pipe\\video_576856061':
  Duration: N/A, start: 0.000000, bitrate: 746496 kb/s
  Stream #0:0: Video: rawvideo, 1 reference frame (Y1[0][16] / 0x10003159), gray16le(pc, bt709/bt709/linear), 720x540, 746496 kb/s, 120 fps, 120 tbr, 120 tbn
 
[out#0/mp4 @ 000001f99505bd40] No explicit maps, mapping streams automatically...
[vost#0:0/hevc_nvenc @ 000001f995a05ac0] Created video stream from input stream 0:0
[Parsed_scale_0 @ 000001f995044900] w:iw h:ih flags:'' interl:0
[Parsed_scale_2 @ 000001f995044cc0] w:iw h:ih flags:'' interl:0
 
Stream mapping:
  Stream #0:0 -> #0:0 (rawvideo (native) -> hevc (hevc_nvenc))
 
[vost#0:0/hevc_nvenc @ 000001f995a05ac0] Starting thread...
[vf#0:0 @ 000001f995a21240] Starting thread...
[vist#0:0/rawvideo @ 000001f99505b5c0] [dec:rawvideo @ 000001f9955ccfc0] Starting thread...
[in#0/rawvideo @ 000001f99504a480] Starting thread...
 
Press [q] to stop, [?] for help
```
This seems "as expected" and has no warnings.

Applying the second stage encoder to the output of that test recording went fine, without any modifications.

I think this is ready to be merged @bruno-f-cruz

**Review by bruno-f-cruz — APPROVED** [review]
Codec runs in bonsai with the ffmpeg @galenlynch listed in the log. Assuming the data-transfer pipeline works, lgtm!

**Pull request merged**
